# Generated by Django 5.2.5 on 2025-08-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rating",
            name="unique_application",
        ),
    ]
